stages:
  - linting
  - test
  - build
  - deploy

variables:
  GIT_CURL_VERBOSE: 1
  GIT_TRACE: 1
  DOCKER_TLS_CERTDIR: ""

flake8:
  stage: linting
  image: python:3.8
  script:
    - pip install flake8
    - flake8 --verbose .
  allow_failure: true
  tags:
    - docker

docker build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -f Dockerfile.python .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker

deploy-to-dev:
  stage: deploy
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version