stages:
  - linting
  - test
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .
  tags:
    - docker