stages:
  - linting
  - test
  - build
  - deploy

variables:
  GIT_CURL_VERBOSE: 1
  GIT_TRACE: 1
  DOCKER_TLS_CERTDIR: ""

flake8:
  stage: linting
  image: python:3.8
  script:
    - flake8 --verbose .
  allow_failure: true
  tags:
    - docker