version: '3'

services:
  tdm_db:
    container_name: tdm_postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "${TDM_DATABASE_DTBS}"
      POSTGRES_USER: "${TDM_DATABASE_USER}"
      POSTGRES_PASSWORD: "${TDM_DATABASE_PSWD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
     - "5432:5432"
    volumes:
      # - ./data:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    networks:
      - tdm

  tdm_redis:
    image: redis:latest
    container_name: tdm_redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/d–∞ta:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: "${REDIS_PSWD}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DATABASES: "${REDIS_DTBS}"
    depends_on:
      - tdm_db
    networks:
      - tdm
    
  python_server:
    build:
      context: .
      dockerfile: Dockerfile.python
#    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    environment:
      POSTGRES_DB: "${TDM_DATABASE_DTBS}"
      POSTGRES_USER: "${TDM_DATABASE_USER}"
      POSTGRES_PASSWORD: "${TDM_DATABASE_PSWD}"
    depends_on:
      - tdm_redis
    ports:
      - "8000:8000"
    command: python3 /usr/src/app_tdm/manage.py runserver 0.0.0.0:8000
    #command: python3 /usr/src/app_tdm/manage.py migrate && python3 /usr/src/app_tdm/manage.py collectstatic && python3 /usr/src/app_tdm/manage.py createsuperuser && python3 manage.py runserver 0.0.0.0:8000
    #command: bash init.sh && python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app_tdm
    networks:
      - tdm

networks:
  tdm:
    driver: bridge
