- hosts: localhost
  # become: yes
  # become_user: ansible
  tasks:
    - name: Print vars
      ansible.builtin.debug:
        msg: vars {{ ci_registry }} {{ gitlab_ci_token }} {{ ci_job_token }}
    - name: Log into docker registry
      community.docker.docker_login:
        # registry: "{{ ci_registry }}"
        registry_url: https://gl.someproject.ru
        username: rag #"{{ gitlab_ci_token }}"
        password: KDzHhtwAvyJawd78as69 #"{{ ci_job_token }}"

    - name: Pull docker image
      community.docker.docker_image:
        name: "{{ ci_registry_image }}:{{ ci_commit_ref_slug }}"
        repository: $CI_REGISTRY
    
    - name: Run the container
      community.docker.docker_container:
        image: "{{ ci_registry_image }}:{{ ci_commit_ref_slug }}"
        name: tdm_container
        state: started