- hosts: localhost
  become: yes
  become_user: ubuntu
  tasks:
    - name: Log into docker registry
      community.docker.docker_login:
        registry: $CI_REGISTRY
        username: gitlab-ci-token
        password: $CI_JOB_TOKEN

    - name: Pull docker image
      community.docker.docker_image:
        name: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLU
        repository: $CI_REGISTRY
    
    - name: Run the container
      community.docker.docker_container:
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLU
        name: tdm_container
        state: started