# Generated by Django 4.0.3 on 2022-08-27 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
