# Generated by Django 4.0.3 on 2022-08-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0002_alter_task_begin_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_at',
            field=models.DateTimeField(null=True),
        ),
    ]
