# Generated by Django 4.0.3 on 2023-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0003_alter_task_begin_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='diagram_offset_x',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='width',
            field=models.IntegerField(default=400),
        ),
    ]
