# Generated by Django 4.0.3 on 2022-08-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0004_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(to='tudushnik.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='tudushnik.tag'),
        ),
    ]
