# Generated by Django 4.0.3 on 2022-08-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0005_alter_tag_tasks_alter_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tasks',
        ),
    ]
