# Generated by Django 4.0.3 on 2022-08-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0006_remove_tag_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tudushnik.tag'),
        ),
    ]
