# Generated by Django 4.0.3 on 2025-01-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0006_taskparentchild_task_children_taskparentchild_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.TextField(default='#aaaaaa'),
        ),
    ]
