# Generated by Django 4.0.3 on 2022-08-27 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0007_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 22, 16, 52, 662714)),
        ),
    ]
