# Generated by Django 4.0.3 on 2025-08-03 19:36

from django.db import migrations, models
import tudushnik.models.user_profile_settings


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0009_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesettings',
            name='avatar',
            field=models.ImageField(default='user_avatars/default_user_avatar.jpg', storage=tudushnik.models.user_profile_settings.OverwriteStorage(), upload_to=tudushnik.models.user_profile_settings.user_avatar_path),
        ),
    ]
