# Generated by Django 4.0.3 on 2025-08-28 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tudushnik', '0010_userprofilesettings_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='own_users_groups', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, related_name='users_groups', to='tudushnik.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='users_groups', to='tudushnik.tag')),
                ('users', models.ManyToManyField(blank=True, related_name='users_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UsersGroup',
                'verbose_name_plural': 'UsersGroups',
                'ordering': ['-updated_at', 'title'],
            },
        ),
    ]
