# Generated by Django 4.0.3 on 2025-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0011_usersgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='permission_view_project',
            field=models.BooleanField(default=True),
        ),
    ]
