# Generated by Django 4.0.3 on 2025-08-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0012_usersgroup_permission_view_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='permission_view_tasks_list',
            field=models.BooleanField(default=True),
        ),
    ]
