# Generated by Django 4.0.3 on 2025-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0013_usersgroup_permission_view_tasks_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='permission_view_project_tasks',
            field=models.BooleanField(default=True),
        ),
    ]
