# Generated by Django 4.0.3 on 2022-08-28 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0013_alter_task_begin_at_alter_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.AlterField(
            model_name='task',
            name='begin_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 34, 3, 807460, tzinfo=utc)),
        ),
    ]
