# Generated by Django 4.0.3 on 2022-08-28 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0014_remove_task_duration_alter_task_begin_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='begin_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 36, 14, 689133, tzinfo=utc)),
        ),
    ]
