# Generated by Django 4.0.3 on 2025-09-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0014_usersgroup_permission_view_project_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='permission_create_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='permission_delete_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='permission_update_task',
            field=models.BooleanField(default=False),
        ),
    ]
