# Generated by Django 4.0.3 on 2025-09-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0015_usersgroup_permission_create_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
