# Generated by Django 4.0.3 on 2025-10-01 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tudushnik', '0016_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accountable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_accountable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='consultant',
            field=models.ManyToManyField(blank=True, related_name='tasks_consultant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='informed',
            field=models.ManyToManyField(blank=True, related_name='tasks_informed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ManyToManyField(blank=True, related_name='tasks_responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
