# Generated by Django 4.0.3 on 2025-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0017_task_accountable_task_consultant_task_informed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'TaskStatus',
                'verbose_name_plural': 'TaskStatuses',
                'ordering': ['pk'],
            },
        ),
    ]
