# Generated by Django 4.0.3 on 2025-10-05 18:25

from django.db import migrations


def add_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model('tudushnik', 'TaskStatus')
    statuses = [
        'New',
        'In Progress',
        'Done',
        'Paused',
        'On Review',
        'Rejected',
        'In Revision',
        'Closed',
        'Archived',
        'Awaiting Resources',
    ]
    for status in statuses:
        TaskStatus.objects.create(title=status)


class Migration(migrations.Migration):
    dependencies = [
        ('tudushnik', '0018_taskstatus'),
    ]

    operations = [
        migrations.RunPython(add_task_statuses),
    ]
