# Generated by Django 4.0.3 on 2025-10-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0019_auto_20251005_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tudushnik.taskstatus'),
        ),
    ]
