# Generated by Django 4.0.3 on 2026-02-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0020_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=models.TextField(default='#34729f'),
        ),
    ]
