# Generated by Django 4.0.3 on 2026-03-28 18:35

from django.db import migrations, models
import django.db.models.deletion

def add_user_levels(apps, schema_editor):
    UserLevel = apps.get_model('tudushnik', 'UserLevel')
    levels = [
        UserLevel(title='Пассивный', min_points=0, max_points=1000),
        UserLevel(title='Средний', min_points=1000, max_points=2000),
        UserLevel(title='Активный', min_points=2000, max_points=3000),
        UserLevel(title='Предприниматель', min_points=3000, max_points=1000000)
    ]
    UserLevel.objects.bulk_create(levels)


def add_user_ranks(apps, schema_editor):
    UserRank = apps.get_model('tudushnik', 'UserRank')
    ranks = [
        UserRank(title='Новичок', min_points=0, max_points=10000),
        UserRank(title='Освоившийся', min_points=10000, max_points=30000),
        UserRank(title='Продвинутый', min_points=30000, max_points=60000),
        UserRank(title='Эксперт', min_points=60000, max_points=100000),
        UserRank(title='Мудрец', min_points=100000, max_points=1000000),
    ]
    UserRank.objects.bulk_create(ranks)


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0021_tag_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('min_points', models.IntegerField()),
                ('max_points', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UserLevel',
                'verbose_name_plural': 'UserLevels',
                'ordering': ['min_points'],
            },
        ),
        migrations.RunPython(add_user_levels),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('min_points', models.IntegerField()),
                ('max_points', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UserRank',
                'verbose_name_plural': 'UserRanks',
                'ordering': ['min_points'],
            },
        ),
        migrations.RunPython(add_user_ranks),
        migrations.AddField(
            model_name='userprofilesettings',
            name='points_now',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilesettings',
            name='points_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilesettings',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tudushnik.userlevel'),
        ),
        migrations.AddField(
            model_name='userprofilesettings',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tudushnik.userrank'),
        ),
    ]
