# Generated by Django 4.0.3 on 2026-03-28 18:46

from django.db import migrations, models
import django.db.models.deletion


def add_user_events(apps, schema_editor):
    UserEvent = apps.get_model('tudushnik', 'UserEvent')
    user_events = [
        UserEvent(event_type='create_project', title='Создание Проекта', description='Создание Проекта, +500 очков', points_delta=500),
        UserEvent(event_type='create_task', title='Создание Задачи', description='Создание Задачи, +10 очков', points_delta=10),
        UserEvent(event_type='update_task', title='Редактирование Задачи', description='Редактирование Задачи, +10 очков', points_delta=10),
        UserEvent(event_type='create_tag', title='Создание Тега', description='Создание Тега, +50 очков', points_delta=50),
        UserEvent(event_type='update_tag', title='Редактирование Тега', description='Редактирование Тега, +50 очков', points_delta=50),
        UserEvent(event_type='activity_today', title='Сегодня были активны', description='Сегодня были активны, +10 очков', points_delta=10),
        UserEvent(event_type='not_activity_today', title='Сегодня бездействовали', description='Сегодня бездействовали, -10 очков', points_delta=-10)
    ]
    UserEvent.objects.bulk_create(user_events)

class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0022_userlevel_userrank_userprofilesettings_points_now_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('points_delta', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'UserEvent',
                'verbose_name_plural': 'UserEvents',
            },
        ),
        migrations.RunPython(add_user_events),
        migrations.CreateModel(
            name='UserEventSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=150)),
                ('event_description', models.TextField(blank=True)),
                ('event_points_delta', models.FloatField(default=0)),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('user_points_after_event', models.FloatField(default=0)),
                ('user_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tudushnik.userprofilesettings')),
            ],
            options={
                'verbose_name': 'UserEventSnapshot',
                'verbose_name_plural': 'UserEventSnapshots',
                'ordering': ['happened_at'],
            },
        ),
    ]
