# Generated by Django 4.0.3 on 2026-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0023_userevent_usereventsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='title',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Paused', 'Paused'), ('On Review', 'On Review'), ('Rejected', 'Rejected'), ('In Revision', 'In Revision'), ('Closed', 'Closed'), ('Archived', 'Archived'), ('Awaiting Resources', 'Awaiting Resources')], max_length=50, unique=True),
        ),
    ]
