# Generated by Django 4.0.3 on 2026-05-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0025_mindmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=200)),
                ('height', models.IntegerField(default=100)),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tudushnik.mindmap')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps', to='tudushnik.task')),
            ],
            options={
                'verbose_name': 'TaskMindMap',
                'verbose_name_plural': 'TasksMindMaps',
            },
        ),
    ]
