# Generated by Django 4.0.3 on 2026-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0026_taskmindmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskparentchild',
            name='curve',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
