# Generated by Django 4.0.3 on 2026-09-05 14:27

from django.db import migrations, models

def set_default_colors(apps, schema_editor):
    TaskStatus = apps.get_model('tudushnik', 'TaskStatus')
    
    # Словарь соответствий: статус -> (color, text_color)
    colors_map = {
        'New': ('#9FD978', '#28582E'),
        'In Progress': ('#6A00FF', '#FFFFFF'),
        'Done': ('#458A49', '#FFFFFF'),
        'Paused': ('#85D1F5', '#FFFFFF'),
        'On Review': ('#F0A30A', '#FFFFFF'),
        'Rejected': ('#E54E4E', '#FFFFFF'),
        'In Revision': ('#AF01E5', '#FFFFFF'),
        'Closed': ('#6D6D6D', '#FFFFFF'),
        'Archived': ('#9D9D9D', '#FFFFFF'),
        'Awaiting Resources': ('#FFFF88', '#FFFFFF'),
    }

    for title, (color, text_color) in colors_map.items():
        try:
            status = TaskStatus.objects.get(title=title)
            status.color = color
            status.text_color = text_color
            status.save(update_fields=['color', 'text_color'])
        except TaskStatus.DoesNotExist:
            # Если запись еще не создана, можно создать её здесь или игнорировать
            pass

def reverse_set_default_colors(apps, schema_editor):
    TaskStatus = apps.get_model('tudushnik', 'TaskStatus')
    TaskStatus.objects.update(color='#FFFFFF', text_color='#000000')

class Migration(migrations.Migration):

    dependencies = [
        ('tudushnik', '0027_taskparentchild_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.RunPython(set_default_colors, reverse_set_default_colors),
    ]
